name: Lint All Things
on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4.6.2
        env:
          VALIDATE_ALL_CODEBASE: true
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          LINTER_RULES_PATH: /
          IGNORE_GITIGNORED_FILES: true

          MARKDOWN_CONFIG_FILE: .markdownlint.yml
          VALIDATE_MARKDOWN: true
